--------------------------------------------------------
--  颇老捞 积己凳 - 老夸老-11岿-01-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "PROJECT1"."USERS" 
   (	"ID" VARCHAR2(50 BYTE), 
	"PW" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"STAT" CHAR(1 BYTE) DEFAULT 0, 
	"AUTH" CHAR(1 BYTE) DEFAULT 1, 
	"NAME" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"IDX" NUMBER(*,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT1"."USERS_PK" ON "PROJECT1"."USERS" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "PROJECT1"."USERS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT1"."USERS" MODIFY ("PW" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT1"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT1"."USERS" MODIFY ("STAT" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT1"."USERS" MODIFY ("AUTH" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT1"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT1"."USERS" MODIFY ("IDX" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT1"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE"  ENABLE;
